/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interficie;

/**
 *
 * @author jordi.guiu.pujols
 */
public class Identificacio extends javax.swing.JFrame {

    /**
     * Creates new form Identificacio
     */
    public Identificacio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titol = new javax.swing.JTextArea();
        crea_user = new javax.swing.JTextField();
        esborra_user = new javax.swing.JTextField();
        carrega_user = new javax.swing.JTextField();
        fons = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(690, 4490));
        setMinimumSize(new java.awt.Dimension(688, 488));
        getContentPane().setLayout(null);

        titol.setEditable(false);
        titol.setBackground(new java.awt.Color(0, 0, 0));
        titol.setColumns(20);
        titol.setFont(new java.awt.Font("Rockwell", 1, 60)); // NOI18N
        titol.setForeground(new java.awt.Color(255, 255, 255));
        titol.setRows(5);
        titol.setText("HIDATO");
        titol.setAutoscrolls(false);
        titol.setBorder(null);
        titol.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titol.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        titol.setRequestFocusEnabled(false);
        titol.setSelectionColor(new java.awt.Color(255, 255, 255));
        titol.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(titol);
        titol.setBounds(208, 94, 260, 60);
        titol.getAccessibleContext().setAccessibleName("");
        titol.getAccessibleContext().setAccessibleDescription("");

        crea_user.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        crea_user.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crea_user.setText("CREAR USUARI");
        crea_user.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        crea_user.setRequestFocusEnabled(false);
        crea_user.setSelectionColor(new java.awt.Color(153, 153, 153));
        crea_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crea_userMouseClicked(evt);
            }
        });
        crea_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crea_userActionPerformed(evt);
            }
        });
        getContentPane().add(crea_user);
        crea_user.setBounds(270, 260, 143, 28);

        esborra_user.setEditable(false);
        esborra_user.setBackground(new java.awt.Color(255, 255, 255));
        esborra_user.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        esborra_user.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        esborra_user.setText("ESBORRA USUARI");
        esborra_user.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        esborra_user.setRequestFocusEnabled(false);
        esborra_user.setSelectionColor(new java.awt.Color(153, 153, 153));
        esborra_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                esborra_userMouseClicked(evt);
            }
        });
        esborra_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esborra_userActionPerformed(evt);
            }
        });
        getContentPane().add(esborra_user);
        esborra_user.setBounds(260, 360, 171, 28);

        carrega_user.setEditable(false);
        carrega_user.setBackground(new java.awt.Color(255, 255, 255));
        carrega_user.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        carrega_user.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        carrega_user.setText("CARREGA USUARI");
        carrega_user.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        carrega_user.setRequestFocusEnabled(false);
        carrega_user.setSelectionColor(new java.awt.Color(153, 153, 153));
        carrega_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carrega_userMouseClicked(evt);
            }
        });
        carrega_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carrega_userActionPerformed(evt);
            }
        });
        getContentPane().add(carrega_user);
        carrega_user.setBounds(260, 310, 171, 28);
        getContentPane().add(fons);
        fons.setBounds(0, 0, 860, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void esborra_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esborra_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_esborra_userActionPerformed

    private void crea_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crea_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crea_userActionPerformed

    private void crea_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crea_userMouseClicked
        // TODO add your handling code here:
        Crea obj = new Crea();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_crea_userMouseClicked

    private void esborra_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_esborra_userMouseClicked
        // TODO add your handling code here:
        Esborra obj = new Esborra();
        obj.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_esborra_userMouseClicked

    private void carrega_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carrega_userMouseClicked
        // TODO add your handling code here:
        Carrega obj = new Carrega();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_carrega_userMouseClicked

    private void carrega_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carrega_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carrega_userActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Identificacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Identificacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Identificacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Identificacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Identificacio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField carrega_user;
    private javax.swing.JTextField crea_user;
    private javax.swing.JTextField esborra_user;
    private javax.swing.JLabel fons;
    private javax.swing.JTextArea titol;
    // End of variables declaration//GEN-END:variables
}
