/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interficie;

/**
 *
 * @author jordi.guiu.pujols
 */
public class Jugar8 extends javax.swing.JFrame {

    /**
     * Creates new form Identificacio
     */
    public Jugar8() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titol = new javax.swing.JTextArea();
        numeros = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        enrere = new javax.swing.JButton();
        primera33 = new javax.swing.JTextField();
        primera83 = new javax.swing.JTextField();
        primera84 = new javax.swing.JTextField();
        primera85 = new javax.swing.JTextField();
        primera86 = new javax.swing.JTextField();
        primera87 = new javax.swing.JTextField();
        primera88 = new javax.swing.JTextField();
        primera89 = new javax.swing.JTextField();
        primera90 = new javax.swing.JTextField();
        primera91 = new javax.swing.JTextField();
        primera92 = new javax.swing.JTextField();
        primera93 = new javax.swing.JTextField();
        primera94 = new javax.swing.JTextField();
        primera95 = new javax.swing.JTextField();
        primera96 = new javax.swing.JTextField();
        primera97 = new javax.swing.JTextField();
        primera98 = new javax.swing.JTextField();
        primera99 = new javax.swing.JTextField();
        primera100 = new javax.swing.JTextField();
        primera101 = new javax.swing.JTextField();
        primera102 = new javax.swing.JTextField();
        primera103 = new javax.swing.JTextField();
        primera104 = new javax.swing.JTextField();
        primera105 = new javax.swing.JTextField();
        primera106 = new javax.swing.JTextField();
        primera107 = new javax.swing.JTextField();
        primera108 = new javax.swing.JTextField();
        primera109 = new javax.swing.JTextField();
        primera110 = new javax.swing.JTextField();
        primera111 = new javax.swing.JTextField();
        primera112 = new javax.swing.JTextField();
        primera113 = new javax.swing.JTextField();
        primera114 = new javax.swing.JTextField();
        primera115 = new javax.swing.JTextField();
        primera116 = new javax.swing.JTextField();
        primera117 = new javax.swing.JTextField();
        primera118 = new javax.swing.JTextField();
        primera119 = new javax.swing.JTextField();
        primera120 = new javax.swing.JTextField();
        primera121 = new javax.swing.JTextField();
        primera122 = new javax.swing.JTextField();
        primera123 = new javax.swing.JTextField();
        primera124 = new javax.swing.JTextField();
        primera125 = new javax.swing.JTextField();
        primera126 = new javax.swing.JTextField();
        primera127 = new javax.swing.JTextField();
        primera128 = new javax.swing.JTextField();
        primera129 = new javax.swing.JTextField();
        primera130 = new javax.swing.JTextField();
        primera131 = new javax.swing.JTextField();
        primera132 = new javax.swing.JTextField();
        primera133 = new javax.swing.JTextField();
        primera134 = new javax.swing.JTextField();
        primera135 = new javax.swing.JTextField();
        primera136 = new javax.swing.JTextField();
        primera137 = new javax.swing.JTextField();
        primera138 = new javax.swing.JTextField();
        primera139 = new javax.swing.JTextField();
        primera140 = new javax.swing.JTextField();
        primera141 = new javax.swing.JTextField();
        primera142 = new javax.swing.JTextField();
        primera143 = new javax.swing.JTextField();
        primera144 = new javax.swing.JTextField();
        primera145 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        numeros1 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(688, 488));
        getContentPane().setLayout(null);

        titol.setEditable(false);
        titol.setBackground(new java.awt.Color(0, 0, 0));
        titol.setColumns(20);
        titol.setFont(new java.awt.Font("Rockwell", 1, 60)); // NOI18N
        titol.setForeground(new java.awt.Color(255, 255, 255));
        titol.setRows(5);
        titol.setText("HIDATO");
        titol.setAutoscrolls(false);
        titol.setBorder(null);
        titol.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titol.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        titol.setRequestFocusEnabled(false);
        titol.setSelectionColor(new java.awt.Color(255, 255, 255));
        titol.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(titol);
        titol.setBounds(160, 50, 260, 60);

        numeros.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numeros.setText("Números:");
        getContentPane().add(numeros);
        numeros.setBounds(510, 100, 80, 40);

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(450, 160, 50, 50);

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(520, 160, 50, 50);

        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(590, 160, 50, 50);

        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(450, 230, 50, 50);

        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(520, 230, 50, 50);

        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(590, 230, 50, 50);

        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(450, 300, 50, 50);

        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(520, 300, 50, 50);

        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(590, 300, 50, 50);

        enrere.setBackground(new java.awt.Color(0, 0, 0));
        enrere.setForeground(new java.awt.Color(255, 255, 255));
        enrere.setText("Enrere");
        enrere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrereActionPerformed(evt);
            }
        });
        enrere.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enrereKeyPressed(evt);
            }
        });
        getContentPane().add(enrere);
        enrere.setBounds(610, 430, 65, 23);

        primera33.setEditable(false);
        primera33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera33MouseClicked(evt);
            }
        });
        getContentPane().add(primera33);
        primera33.setBounds(260, 300, 30, 30);

        primera83.setEditable(false);
        primera83.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera83.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera83MouseClicked(evt);
            }
        });
        getContentPane().add(primera83);
        primera83.setBounds(170, 150, 30, 30);

        primera84.setEditable(false);
        primera84.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera84.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera84MouseClicked(evt);
            }
        });
        getContentPane().add(primera84);
        primera84.setBounds(200, 150, 30, 30);

        primera85.setEditable(false);
        primera85.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera85.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera85MouseClicked(evt);
            }
        });
        getContentPane().add(primera85);
        primera85.setBounds(230, 150, 30, 30);

        primera86.setEditable(false);
        primera86.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera86.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera86MouseClicked(evt);
            }
        });
        getContentPane().add(primera86);
        primera86.setBounds(260, 150, 30, 30);

        primera87.setEditable(false);
        primera87.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera87.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera87MouseClicked(evt);
            }
        });
        getContentPane().add(primera87);
        primera87.setBounds(290, 150, 30, 30);

        primera88.setEditable(false);
        primera88.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera88.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera88MouseClicked(evt);
            }
        });
        getContentPane().add(primera88);
        primera88.setBounds(320, 150, 30, 30);

        primera89.setEditable(false);
        primera89.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera89.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera89MouseClicked(evt);
            }
        });
        getContentPane().add(primera89);
        primera89.setBounds(350, 150, 30, 30);

        primera90.setEditable(false);
        primera90.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera90.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera90MouseClicked(evt);
            }
        });
        getContentPane().add(primera90);
        primera90.setBounds(380, 150, 30, 30);

        primera91.setEditable(false);
        primera91.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera91.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera91MouseClicked(evt);
            }
        });
        getContentPane().add(primera91);
        primera91.setBounds(170, 180, 30, 30);

        primera92.setEditable(false);
        primera92.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera92.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera92MouseClicked(evt);
            }
        });
        getContentPane().add(primera92);
        primera92.setBounds(170, 210, 30, 30);

        primera93.setEditable(false);
        primera93.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera93.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera93MouseClicked(evt);
            }
        });
        getContentPane().add(primera93);
        primera93.setBounds(170, 240, 30, 30);

        primera94.setEditable(false);
        primera94.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera94.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera94MouseClicked(evt);
            }
        });
        getContentPane().add(primera94);
        primera94.setBounds(170, 270, 30, 30);

        primera95.setEditable(false);
        primera95.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera95.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera95MouseClicked(evt);
            }
        });
        getContentPane().add(primera95);
        primera95.setBounds(170, 300, 30, 30);

        primera96.setEditable(false);
        primera96.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera96.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera96MouseClicked(evt);
            }
        });
        getContentPane().add(primera96);
        primera96.setBounds(170, 330, 30, 30);

        primera97.setEditable(false);
        primera97.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera97.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera97MouseClicked(evt);
            }
        });
        getContentPane().add(primera97);
        primera97.setBounds(170, 360, 30, 30);

        primera98.setEditable(false);
        primera98.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera98.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera98MouseClicked(evt);
            }
        });
        getContentPane().add(primera98);
        primera98.setBounds(200, 360, 30, 30);

        primera99.setEditable(false);
        primera99.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera99.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera99MouseClicked(evt);
            }
        });
        getContentPane().add(primera99);
        primera99.setBounds(230, 360, 30, 30);

        primera100.setEditable(false);
        primera100.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera100.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera100MouseClicked(evt);
            }
        });
        getContentPane().add(primera100);
        primera100.setBounds(200, 330, 30, 30);

        primera101.setEditable(false);
        primera101.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera101.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera101MouseClicked(evt);
            }
        });
        getContentPane().add(primera101);
        primera101.setBounds(200, 300, 30, 30);

        primera102.setEditable(false);
        primera102.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera102.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera102MouseClicked(evt);
            }
        });
        getContentPane().add(primera102);
        primera102.setBounds(200, 270, 30, 30);

        primera103.setEditable(false);
        primera103.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera103.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera103MouseClicked(evt);
            }
        });
        getContentPane().add(primera103);
        primera103.setBounds(200, 240, 30, 30);

        primera104.setEditable(false);
        primera104.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera104.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera104MouseClicked(evt);
            }
        });
        getContentPane().add(primera104);
        primera104.setBounds(200, 210, 30, 30);

        primera105.setEditable(false);
        primera105.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera105.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera105MouseClicked(evt);
            }
        });
        getContentPane().add(primera105);
        primera105.setBounds(200, 180, 30, 30);

        primera106.setEditable(false);
        primera106.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera106.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera106MouseClicked(evt);
            }
        });
        getContentPane().add(primera106);
        primera106.setBounds(230, 180, 30, 30);

        primera107.setEditable(false);
        primera107.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera107.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera107MouseClicked(evt);
            }
        });
        getContentPane().add(primera107);
        primera107.setBounds(260, 180, 30, 30);

        primera108.setEditable(false);
        primera108.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera108.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera108MouseClicked(evt);
            }
        });
        getContentPane().add(primera108);
        primera108.setBounds(290, 180, 30, 30);

        primera109.setEditable(false);
        primera109.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera109.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera109MouseClicked(evt);
            }
        });
        getContentPane().add(primera109);
        primera109.setBounds(320, 180, 30, 30);

        primera110.setEditable(false);
        primera110.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera110.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera110MouseClicked(evt);
            }
        });
        getContentPane().add(primera110);
        primera110.setBounds(350, 180, 30, 30);

        primera111.setEditable(false);
        primera111.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera111.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera111MouseClicked(evt);
            }
        });
        getContentPane().add(primera111);
        primera111.setBounds(380, 180, 30, 30);

        primera112.setEditable(false);
        primera112.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera112.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera112MouseClicked(evt);
            }
        });
        getContentPane().add(primera112);
        primera112.setBounds(380, 210, 30, 30);

        primera113.setEditable(false);
        primera113.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera113.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera113MouseClicked(evt);
            }
        });
        getContentPane().add(primera113);
        primera113.setBounds(380, 240, 30, 30);

        primera114.setEditable(false);
        primera114.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera114.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera114MouseClicked(evt);
            }
        });
        getContentPane().add(primera114);
        primera114.setBounds(380, 270, 30, 30);

        primera115.setEditable(false);
        primera115.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera115.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera115MouseClicked(evt);
            }
        });
        getContentPane().add(primera115);
        primera115.setBounds(380, 300, 30, 30);

        primera116.setEditable(false);
        primera116.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera116.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera116MouseClicked(evt);
            }
        });
        getContentPane().add(primera116);
        primera116.setBounds(380, 330, 30, 30);

        primera117.setEditable(false);
        primera117.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera117.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera117MouseClicked(evt);
            }
        });
        getContentPane().add(primera117);
        primera117.setBounds(380, 360, 30, 30);

        primera118.setEditable(false);
        primera118.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera118.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera118MouseClicked(evt);
            }
        });
        getContentPane().add(primera118);
        primera118.setBounds(350, 360, 30, 30);

        primera119.setEditable(false);
        primera119.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera119.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera119MouseClicked(evt);
            }
        });
        getContentPane().add(primera119);
        primera119.setBounds(320, 360, 30, 30);

        primera120.setEditable(false);
        primera120.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera120.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera120MouseClicked(evt);
            }
        });
        getContentPane().add(primera120);
        primera120.setBounds(290, 360, 30, 30);

        primera121.setEditable(false);
        primera121.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera121.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera121MouseClicked(evt);
            }
        });
        getContentPane().add(primera121);
        primera121.setBounds(260, 360, 30, 30);

        primera122.setEditable(false);
        primera122.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera122.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera122MouseClicked(evt);
            }
        });
        getContentPane().add(primera122);
        primera122.setBounds(230, 330, 30, 30);

        primera123.setEditable(false);
        primera123.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera123.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera123MouseClicked(evt);
            }
        });
        getContentPane().add(primera123);
        primera123.setBounds(260, 330, 30, 30);

        primera124.setEditable(false);
        primera124.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera124.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera124MouseClicked(evt);
            }
        });
        getContentPane().add(primera124);
        primera124.setBounds(290, 330, 30, 30);

        primera125.setEditable(false);
        primera125.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera125.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera125MouseClicked(evt);
            }
        });
        getContentPane().add(primera125);
        primera125.setBounds(320, 330, 30, 30);

        primera126.setEditable(false);
        primera126.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera126.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera126MouseClicked(evt);
            }
        });
        getContentPane().add(primera126);
        primera126.setBounds(350, 330, 30, 30);

        primera127.setEditable(false);
        primera127.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera127.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera127MouseClicked(evt);
            }
        });
        getContentPane().add(primera127);
        primera127.setBounds(350, 300, 30, 30);

        primera128.setEditable(false);
        primera128.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera128.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera128MouseClicked(evt);
            }
        });
        getContentPane().add(primera128);
        primera128.setBounds(350, 270, 30, 30);

        primera129.setEditable(false);
        primera129.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera129.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera129MouseClicked(evt);
            }
        });
        getContentPane().add(primera129);
        primera129.setBounds(350, 240, 30, 30);

        primera130.setEditable(false);
        primera130.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera130.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera130MouseClicked(evt);
            }
        });
        getContentPane().add(primera130);
        primera130.setBounds(350, 210, 30, 30);

        primera131.setEditable(false);
        primera131.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera131.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera131MouseClicked(evt);
            }
        });
        getContentPane().add(primera131);
        primera131.setBounds(320, 210, 30, 30);

        primera132.setEditable(false);
        primera132.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera132.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera132MouseClicked(evt);
            }
        });
        getContentPane().add(primera132);
        primera132.setBounds(320, 240, 30, 30);

        primera133.setEditable(false);
        primera133.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera133.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera133MouseClicked(evt);
            }
        });
        getContentPane().add(primera133);
        primera133.setBounds(320, 270, 30, 30);

        primera134.setEditable(false);
        primera134.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera134.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera134MouseClicked(evt);
            }
        });
        getContentPane().add(primera134);
        primera134.setBounds(320, 300, 30, 30);

        primera135.setEditable(false);
        primera135.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera135.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera135MouseClicked(evt);
            }
        });
        getContentPane().add(primera135);
        primera135.setBounds(290, 300, 30, 30);

        primera136.setEditable(false);
        primera136.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera136.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera136MouseClicked(evt);
            }
        });
        getContentPane().add(primera136);
        primera136.setBounds(290, 270, 30, 30);

        primera137.setEditable(false);
        primera137.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera137.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera137MouseClicked(evt);
            }
        });
        getContentPane().add(primera137);
        primera137.setBounds(290, 240, 30, 30);

        primera138.setEditable(false);
        primera138.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera138.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera138MouseClicked(evt);
            }
        });
        getContentPane().add(primera138);
        primera138.setBounds(290, 210, 30, 30);

        primera139.setEditable(false);
        primera139.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera139.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera139MouseClicked(evt);
            }
        });
        getContentPane().add(primera139);
        primera139.setBounds(260, 210, 30, 30);

        primera140.setEditable(false);
        primera140.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera140.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera140MouseClicked(evt);
            }
        });
        getContentPane().add(primera140);
        primera140.setBounds(230, 210, 30, 30);

        primera141.setEditable(false);
        primera141.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera141.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera141MouseClicked(evt);
            }
        });
        getContentPane().add(primera141);
        primera141.setBounds(230, 240, 30, 30);

        primera142.setEditable(false);
        primera142.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera142.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera142MouseClicked(evt);
            }
        });
        getContentPane().add(primera142);
        primera142.setBounds(260, 240, 30, 30);

        primera143.setEditable(false);
        primera143.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera143.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera143MouseClicked(evt);
            }
        });
        getContentPane().add(primera143);
        primera143.setBounds(260, 270, 30, 30);

        primera144.setEditable(false);
        primera144.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera144.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera144MouseClicked(evt);
            }
        });
        getContentPane().add(primera144);
        primera144.setBounds(230, 270, 30, 30);

        primera145.setEditable(false);
        primera145.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primera145.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primera145MouseClicked(evt);
            }
        });
        getContentPane().add(primera145);
        primera145.setBounds(230, 300, 30, 30);

        jButton10.setText("Resoldre");
        getContentPane().add(jButton10);
        jButton10.setBounds(450, 370, 79, 23);

        numeros1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numeros1.setText("Marques:");
        getContentPane().add(numeros1);
        numeros1.setBounds(30, 200, 80, 40);

        jButton11.setText("Treure marca");
        getContentPane().add(jButton11);
        jButton11.setBounds(20, 160, 110, 23);

        jButton12.setText("Afegir marca");
        getContentPane().add(jButton12);
        jButton12.setBounds(20, 120, 100, 23);

        jTextField1.setEditable(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(30, 250, 80, 140);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void enrereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrereActionPerformed
        // TODO add your handling code here:
        Menu obj = new Menu();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_enrereActionPerformed

    private void enrereKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enrereKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_enrereKeyPressed

    private void primera33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera33MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera33MouseClicked

    private void primera83MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera83MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera83MouseClicked

    private void primera84MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera84MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera84MouseClicked

    private void primera85MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera85MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera85MouseClicked

    private void primera86MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera86MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera86MouseClicked

    private void primera87MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera87MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera87MouseClicked

    private void primera88MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera88MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera88MouseClicked

    private void primera89MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera89MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera89MouseClicked

    private void primera90MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera90MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera90MouseClicked

    private void primera91MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera91MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera91MouseClicked

    private void primera92MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera92MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera92MouseClicked

    private void primera93MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera93MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera93MouseClicked

    private void primera94MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera94MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera94MouseClicked

    private void primera95MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera95MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera95MouseClicked

    private void primera96MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera96MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera96MouseClicked

    private void primera97MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera97MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera97MouseClicked

    private void primera98MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera98MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera98MouseClicked

    private void primera99MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera99MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera99MouseClicked

    private void primera100MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera100MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera100MouseClicked

    private void primera101MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera101MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera101MouseClicked

    private void primera102MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera102MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera102MouseClicked

    private void primera103MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera103MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera103MouseClicked

    private void primera104MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera104MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera104MouseClicked

    private void primera105MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera105MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera105MouseClicked

    private void primera106MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera106MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera106MouseClicked

    private void primera107MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera107MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera107MouseClicked

    private void primera108MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera108MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera108MouseClicked

    private void primera109MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera109MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera109MouseClicked

    private void primera110MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera110MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera110MouseClicked

    private void primera111MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera111MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera111MouseClicked

    private void primera112MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera112MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera112MouseClicked

    private void primera113MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera113MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera113MouseClicked

    private void primera114MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera114MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera114MouseClicked

    private void primera115MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera115MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera115MouseClicked

    private void primera116MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera116MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera116MouseClicked

    private void primera117MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera117MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera117MouseClicked

    private void primera118MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera118MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera118MouseClicked

    private void primera119MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera119MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera119MouseClicked

    private void primera120MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera120MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera120MouseClicked

    private void primera121MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera121MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera121MouseClicked

    private void primera122MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera122MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera122MouseClicked

    private void primera123MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera123MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera123MouseClicked

    private void primera124MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera124MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera124MouseClicked

    private void primera125MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera125MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera125MouseClicked

    private void primera126MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera126MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera126MouseClicked

    private void primera127MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera127MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera127MouseClicked

    private void primera128MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera128MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera128MouseClicked

    private void primera129MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera129MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera129MouseClicked

    private void primera130MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera130MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera130MouseClicked

    private void primera131MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera131MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera131MouseClicked

    private void primera132MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera132MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera132MouseClicked

    private void primera133MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera133MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera133MouseClicked

    private void primera134MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera134MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera134MouseClicked

    private void primera135MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera135MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera135MouseClicked

    private void primera136MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera136MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera136MouseClicked

    private void primera137MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera137MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera137MouseClicked

    private void primera138MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera138MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera138MouseClicked

    private void primera139MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera139MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera139MouseClicked

    private void primera140MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera140MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera140MouseClicked

    private void primera141MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera141MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera141MouseClicked

    private void primera142MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera142MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera142MouseClicked

    private void primera143MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera143MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera143MouseClicked

    private void primera144MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera144MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera144MouseClicked

    private void primera145MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primera145MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_primera145MouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jugar8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jugar8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jugar8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jugar8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jugar8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enrere;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel numeros;
    private javax.swing.JLabel numeros1;
    private javax.swing.JTextField primera100;
    private javax.swing.JTextField primera101;
    private javax.swing.JTextField primera102;
    private javax.swing.JTextField primera103;
    private javax.swing.JTextField primera104;
    private javax.swing.JTextField primera105;
    private javax.swing.JTextField primera106;
    private javax.swing.JTextField primera107;
    private javax.swing.JTextField primera108;
    private javax.swing.JTextField primera109;
    private javax.swing.JTextField primera110;
    private javax.swing.JTextField primera111;
    private javax.swing.JTextField primera112;
    private javax.swing.JTextField primera113;
    private javax.swing.JTextField primera114;
    private javax.swing.JTextField primera115;
    private javax.swing.JTextField primera116;
    private javax.swing.JTextField primera117;
    private javax.swing.JTextField primera118;
    private javax.swing.JTextField primera119;
    private javax.swing.JTextField primera120;
    private javax.swing.JTextField primera121;
    private javax.swing.JTextField primera122;
    private javax.swing.JTextField primera123;
    private javax.swing.JTextField primera124;
    private javax.swing.JTextField primera125;
    private javax.swing.JTextField primera126;
    private javax.swing.JTextField primera127;
    private javax.swing.JTextField primera128;
    private javax.swing.JTextField primera129;
    private javax.swing.JTextField primera130;
    private javax.swing.JTextField primera131;
    private javax.swing.JTextField primera132;
    private javax.swing.JTextField primera133;
    private javax.swing.JTextField primera134;
    private javax.swing.JTextField primera135;
    private javax.swing.JTextField primera136;
    private javax.swing.JTextField primera137;
    private javax.swing.JTextField primera138;
    private javax.swing.JTextField primera139;
    private javax.swing.JTextField primera140;
    private javax.swing.JTextField primera141;
    private javax.swing.JTextField primera142;
    private javax.swing.JTextField primera143;
    private javax.swing.JTextField primera144;
    private javax.swing.JTextField primera145;
    private javax.swing.JTextField primera33;
    private javax.swing.JTextField primera83;
    private javax.swing.JTextField primera84;
    private javax.swing.JTextField primera85;
    private javax.swing.JTextField primera86;
    private javax.swing.JTextField primera87;
    private javax.swing.JTextField primera88;
    private javax.swing.JTextField primera89;
    private javax.swing.JTextField primera90;
    private javax.swing.JTextField primera91;
    private javax.swing.JTextField primera92;
    private javax.swing.JTextField primera93;
    private javax.swing.JTextField primera94;
    private javax.swing.JTextField primera95;
    private javax.swing.JTextField primera96;
    private javax.swing.JTextField primera97;
    private javax.swing.JTextField primera98;
    private javax.swing.JTextField primera99;
    private javax.swing.JTextArea titol;
    // End of variables declaration//GEN-END:variables
}
