/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interficie.jugar;


import static drivers.Controlador.*;
import interficie.Menu;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import static javax.swing.JOptionPane.WARNING_MESSAGE;

/**
 *
 * @author jordi.guiu.pujols
 */
public class Jugar7 extends javax.swing.JFrame {
    public static String us;
    public static int dif;
    public static int size = 7;

    /**
     * Creates new form Identificacio
     */
    public Jugar7(String usuari, int dificultat) {
        initComponents();
        setSize(1000,600);
        setLocationRelativeTo(null);
        setResizable(false);
        us = usuari;
        dif = dificultat;
        initialitzararraytextfield();
        myinitComponents();
    }
    
    void initialitzararraytextfield(){
        txtField[0] = c00;
        txtField[1] = c01;
        txtField[2] = c02;
        txtField[3] = c03;
        txtField[4] = c04;
        txtField[5] = c05;
        txtField[6] = c06;
        txtField[7] = c10;
        txtField[8] = c11;
        txtField[9] = c12;
        txtField[10] = c13;
        txtField[11] = c14;
        txtField[12] = c15;
        txtField[13] = c16;
        txtField[14] = c20;
        txtField[15] = c21;
        txtField[16] = c22;
        txtField[17] = c23;
        txtField[18] = c24;
        txtField[19] = c25;
        txtField[20] = c26;
        txtField[21] = c30;
        txtField[22] = c31;
        txtField[23] = c32;
        txtField[24] = c33;
        txtField[25] = c34;
        txtField[26] = c35;
        txtField[27] = c36;
        txtField[28] = c40;
        txtField[29] = c41;
        txtField[30] = c42;
        txtField[31] = c43;
        txtField[32] = c44;
        txtField[33] = c45;
        txtField[34] = c46;
        txtField[35] = c50;
        txtField[36] = c51;
        txtField[37] = c52;
        txtField[38] = c53;
        txtField[39] = c54;
        txtField[40] = c55;
        txtField[41] = c56;
        txtField[42] = c60;
        txtField[43] = c61;
        txtField[44] = c62;
        txtField[45] = c63;
        txtField[46] = c64;
        txtField[47] = c65;
        txtField[48] = c66;
    }
    
    private void myinitComponents() {
        apretat = false;
        ArrayList<Integer> valors = carregarTaulellTemporal();
        començarJoc(dif);
        int ultima = es_ultim();
        String lastnum = Integer.toString(ultima);
        Color color = Color.cyan;
        for (int i = 0; i < valors.size(); ++i){
            tf = txtField[i];
             if (valors.get(i) != 0){
                tf.setText(Integer.toString(valors.get(i)));
                if ("1".equals(tf.getText())) tf.setBackground(color);            
                else if (tf.getText().equals(lastnum)) tf.setBackground(color);
                else if ("-1".equals(tf.getText())){
                    tf.setBackground(Color.black);
                    tf.setText("X");
                }
            }
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titol = new javax.swing.JTextArea();
        numeros = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        enrere = new javax.swing.JButton();
        c52 = new javax.swing.JTextField();
        c00 = new javax.swing.JTextField();
        c01 = new javax.swing.JTextField();
        c02 = new javax.swing.JTextField();
        c03 = new javax.swing.JTextField();
        c04 = new javax.swing.JTextField();
        c60 = new javax.swing.JTextField();
        c10 = new javax.swing.JTextField();
        c20 = new javax.swing.JTextField();
        c30 = new javax.swing.JTextField();
        c40 = new javax.swing.JTextField();
        c50 = new javax.swing.JTextField();
        c51 = new javax.swing.JTextField();
        c41 = new javax.swing.JTextField();
        c31 = new javax.swing.JTextField();
        c21 = new javax.swing.JTextField();
        c11 = new javax.swing.JTextField();
        c12 = new javax.swing.JTextField();
        c13 = new javax.swing.JTextField();
        c14 = new javax.swing.JTextField();
        c15 = new javax.swing.JTextField();
        c25 = new javax.swing.JTextField();
        c35 = new javax.swing.JTextField();
        c45 = new javax.swing.JTextField();
        c55 = new javax.swing.JTextField();
        c54 = new javax.swing.JTextField();
        c44 = new javax.swing.JTextField();
        c34 = new javax.swing.JTextField();
        c24 = new javax.swing.JTextField();
        c23 = new javax.swing.JTextField();
        c22 = new javax.swing.JTextField();
        c33 = new javax.swing.JTextField();
        c32 = new javax.swing.JTextField();
        c42 = new javax.swing.JTextField();
        c43 = new javax.swing.JTextField();
        c53 = new javax.swing.JTextField();
        c05 = new javax.swing.JTextField();
        c06 = new javax.swing.JTextField();
        c16 = new javax.swing.JTextField();
        c26 = new javax.swing.JTextField();
        c36 = new javax.swing.JTextField();
        c46 = new javax.swing.JTextField();
        c56 = new javax.swing.JTextField();
        c66 = new javax.swing.JTextField();
        c65 = new javax.swing.JTextField();
        c64 = new javax.swing.JTextField();
        c63 = new javax.swing.JTextField();
        c62 = new javax.swing.JTextField();
        c61 = new javax.swing.JTextField();
        comprovar = new javax.swing.JButton();
        Autocompletar = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(688, 488));
        getContentPane().setLayout(null);

        titol.setEditable(false);
        titol.setBackground(new java.awt.Color(0, 0, 0));
        titol.setColumns(20);
        titol.setFont(new java.awt.Font("Rockwell", 1, 60)); // NOI18N
        titol.setForeground(new java.awt.Color(255, 255, 255));
        titol.setRows(5);
        titol.setText("HIDATO");
        titol.setAutoscrolls(false);
        titol.setBorder(null);
        titol.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titol.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        titol.setRequestFocusEnabled(false);
        titol.setSelectionColor(new java.awt.Color(255, 255, 255));
        titol.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(titol);
        titol.setBounds(280, 30, 260, 60);

        numeros.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numeros.setText("Números:");
        getContentPane().add(numeros);
        numeros.setBounds(710, 100, 90, 50);

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(650, 160, 60, 60);

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(720, 160, 60, 60);

        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(790, 160, 60, 60);

        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(650, 230, 60, 60);

        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(720, 230, 60, 60);

        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(790, 230, 60, 60);

        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(650, 300, 60, 60);

        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(720, 300, 60, 60);

        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(790, 300, 60, 60);

        enrere.setBackground(new java.awt.Color(0, 0, 0));
        enrere.setForeground(new java.awt.Color(255, 255, 255));
        enrere.setText("Sortir");
        enrere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrereActionPerformed(evt);
            }
        });
        enrere.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enrereKeyPressed(evt);
            }
        });
        getContentPane().add(enrere);
        enrere.setBounds(850, 490, 110, 60);

        c52.setEditable(false);
        c52.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c52MouseClicked(evt);
            }
        });
        getContentPane().add(c52);
        c52.setBounds(350, 360, 40, 40);

        c00.setEditable(false);
        c00.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c00MouseClicked(evt);
            }
        });
        getContentPane().add(c00);
        c00.setBounds(270, 160, 40, 40);

        c01.setEditable(false);
        c01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c01MouseClicked(evt);
            }
        });
        getContentPane().add(c01);
        c01.setBounds(310, 160, 40, 40);

        c02.setEditable(false);
        c02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c02MouseClicked(evt);
            }
        });
        getContentPane().add(c02);
        c02.setBounds(350, 160, 40, 40);

        c03.setEditable(false);
        c03.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c03MouseClicked(evt);
            }
        });
        getContentPane().add(c03);
        c03.setBounds(390, 160, 40, 40);

        c04.setEditable(false);
        c04.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c04MouseClicked(evt);
            }
        });
        getContentPane().add(c04);
        c04.setBounds(430, 160, 40, 40);

        c60.setEditable(false);
        c60.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c60.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c60MouseClicked(evt);
            }
        });
        getContentPane().add(c60);
        c60.setBounds(270, 400, 40, 40);

        c10.setEditable(false);
        c10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c10MouseClicked(evt);
            }
        });
        getContentPane().add(c10);
        c10.setBounds(270, 200, 40, 40);

        c20.setEditable(false);
        c20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c20MouseClicked(evt);
            }
        });
        getContentPane().add(c20);
        c20.setBounds(270, 240, 40, 40);

        c30.setEditable(false);
        c30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c30MouseClicked(evt);
            }
        });
        getContentPane().add(c30);
        c30.setBounds(270, 280, 40, 40);

        c40.setEditable(false);
        c40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c40MouseClicked(evt);
            }
        });
        getContentPane().add(c40);
        c40.setBounds(270, 320, 40, 40);

        c50.setEditable(false);
        c50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c50MouseClicked(evt);
            }
        });
        getContentPane().add(c50);
        c50.setBounds(270, 360, 40, 40);

        c51.setEditable(false);
        c51.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c51MouseClicked(evt);
            }
        });
        getContentPane().add(c51);
        c51.setBounds(310, 360, 40, 40);

        c41.setEditable(false);
        c41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c41MouseClicked(evt);
            }
        });
        getContentPane().add(c41);
        c41.setBounds(310, 320, 40, 40);

        c31.setEditable(false);
        c31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c31MouseClicked(evt);
            }
        });
        getContentPane().add(c31);
        c31.setBounds(310, 280, 40, 40);

        c21.setEditable(false);
        c21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c21MouseClicked(evt);
            }
        });
        getContentPane().add(c21);
        c21.setBounds(310, 240, 40, 40);

        c11.setEditable(false);
        c11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c11MouseClicked(evt);
            }
        });
        getContentPane().add(c11);
        c11.setBounds(310, 200, 40, 40);

        c12.setEditable(false);
        c12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c12MouseClicked(evt);
            }
        });
        getContentPane().add(c12);
        c12.setBounds(350, 200, 40, 40);

        c13.setEditable(false);
        c13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c13MouseClicked(evt);
            }
        });
        getContentPane().add(c13);
        c13.setBounds(390, 200, 40, 40);

        c14.setEditable(false);
        c14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c14MouseClicked(evt);
            }
        });
        getContentPane().add(c14);
        c14.setBounds(430, 200, 40, 40);

        c15.setEditable(false);
        c15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c15MouseClicked(evt);
            }
        });
        getContentPane().add(c15);
        c15.setBounds(470, 200, 40, 40);

        c25.setEditable(false);
        c25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c25MouseClicked(evt);
            }
        });
        getContentPane().add(c25);
        c25.setBounds(470, 240, 40, 40);

        c35.setEditable(false);
        c35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c35MouseClicked(evt);
            }
        });
        getContentPane().add(c35);
        c35.setBounds(470, 280, 40, 40);

        c45.setEditable(false);
        c45.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c45MouseClicked(evt);
            }
        });
        getContentPane().add(c45);
        c45.setBounds(470, 320, 40, 40);

        c55.setEditable(false);
        c55.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c55MouseClicked(evt);
            }
        });
        getContentPane().add(c55);
        c55.setBounds(470, 360, 40, 40);

        c54.setEditable(false);
        c54.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c54MouseClicked(evt);
            }
        });
        getContentPane().add(c54);
        c54.setBounds(430, 360, 40, 40);

        c44.setEditable(false);
        c44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c44MouseClicked(evt);
            }
        });
        getContentPane().add(c44);
        c44.setBounds(430, 320, 40, 40);

        c34.setEditable(false);
        c34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c34MouseClicked(evt);
            }
        });
        getContentPane().add(c34);
        c34.setBounds(430, 280, 40, 40);

        c24.setEditable(false);
        c24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c24MouseClicked(evt);
            }
        });
        getContentPane().add(c24);
        c24.setBounds(430, 240, 40, 40);

        c23.setEditable(false);
        c23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c23MouseClicked(evt);
            }
        });
        getContentPane().add(c23);
        c23.setBounds(390, 240, 40, 40);

        c22.setEditable(false);
        c22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c22MouseClicked(evt);
            }
        });
        getContentPane().add(c22);
        c22.setBounds(350, 240, 40, 40);

        c33.setEditable(false);
        c33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c33MouseClicked(evt);
            }
        });
        getContentPane().add(c33);
        c33.setBounds(390, 280, 40, 40);

        c32.setEditable(false);
        c32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c32MouseClicked(evt);
            }
        });
        getContentPane().add(c32);
        c32.setBounds(350, 280, 40, 40);

        c42.setEditable(false);
        c42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c42MouseClicked(evt);
            }
        });
        getContentPane().add(c42);
        c42.setBounds(350, 320, 40, 40);

        c43.setEditable(false);
        c43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c43MouseClicked(evt);
            }
        });
        getContentPane().add(c43);
        c43.setBounds(390, 320, 40, 40);

        c53.setEditable(false);
        c53.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c53MouseClicked(evt);
            }
        });
        getContentPane().add(c53);
        c53.setBounds(390, 360, 40, 40);

        c05.setEditable(false);
        c05.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c05MouseClicked(evt);
            }
        });
        getContentPane().add(c05);
        c05.setBounds(470, 160, 40, 40);

        c06.setEditable(false);
        c06.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c06MouseClicked(evt);
            }
        });
        getContentPane().add(c06);
        c06.setBounds(510, 160, 40, 40);

        c16.setEditable(false);
        c16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c16MouseClicked(evt);
            }
        });
        getContentPane().add(c16);
        c16.setBounds(510, 200, 40, 40);

        c26.setEditable(false);
        c26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c26MouseClicked(evt);
            }
        });
        getContentPane().add(c26);
        c26.setBounds(510, 240, 40, 40);

        c36.setEditable(false);
        c36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c36MouseClicked(evt);
            }
        });
        getContentPane().add(c36);
        c36.setBounds(510, 280, 40, 40);

        c46.setEditable(false);
        c46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c46MouseClicked(evt);
            }
        });
        getContentPane().add(c46);
        c46.setBounds(510, 320, 40, 40);

        c56.setEditable(false);
        c56.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c56.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c56MouseClicked(evt);
            }
        });
        getContentPane().add(c56);
        c56.setBounds(510, 360, 40, 40);

        c66.setEditable(false);
        c66.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c66.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c66MouseClicked(evt);
            }
        });
        getContentPane().add(c66);
        c66.setBounds(510, 400, 40, 40);

        c65.setEditable(false);
        c65.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c65.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c65MouseClicked(evt);
            }
        });
        getContentPane().add(c65);
        c65.setBounds(470, 400, 40, 40);

        c64.setEditable(false);
        c64.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c64.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c64MouseClicked(evt);
            }
        });
        getContentPane().add(c64);
        c64.setBounds(430, 400, 40, 40);

        c63.setEditable(false);
        c63.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c63.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c63MouseClicked(evt);
            }
        });
        getContentPane().add(c63);
        c63.setBounds(390, 400, 40, 40);

        c62.setEditable(false);
        c62.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c62MouseClicked(evt);
            }
        });
        getContentPane().add(c62);
        c62.setBounds(350, 400, 40, 40);

        c61.setEditable(false);
        c61.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c61.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c61MouseClicked(evt);
            }
        });
        getContentPane().add(c61);
        c61.setBounds(310, 400, 40, 40);

        comprovar.setText("Comprovar");
        comprovar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comprovarMouseClicked(evt);
            }
        });
        comprovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprovarActionPerformed(evt);
            }
        });
        getContentPane().add(comprovar);
        comprovar.setBounds(270, 460, 280, 50);

        Autocompletar.setText("Autocompletar");
        Autocompletar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AutocompletarMouseClicked(evt);
            }
        });
        Autocompletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutocompletarActionPerformed(evt);
            }
        });
        getContentPane().add(Autocompletar);
        Autocompletar.setBounds(40, 450, 130, 70);

        jButton11.setText("Esborrar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(750, 370, 100, 60);

        jButton12.setText("0");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(650, 370, 60, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void boto(String textboto){
        //array dstrings com tantes posicions como caselles. 
        //a cada casella li passem a boto la seva posicio dins larray
        String S = Caselles[i];
        f = Character.getNumericValue(S.charAt(1));
        c =  Character.getNumericValue(S.charAt(2));
        if (textboto == "Esborrar") val = 0;
        else val = Integer.parseInt(tf.getText() + textboto);
        System.out.println(val);
        System.out.println(f);
        System.out.println(c);
        if (afegirmarca){ 
            val = Integer.parseInt(textboto);
            switchAnnotationCasella(val, f, c);
            afegirmarca = false;
        }
        else{
            DefineixCasella(val, f, c,size);
            String afegirstr;
            int afegirint = getCasella(f,c);   
            if (afegirint == 0) afegirstr = null;
            else if (afegirint == -1) afegirstr = "X";
            else afegirstr = String.valueOf(afegirint);
            tf.setText(afegirstr);
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boto(jButton1.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        boto(jButton2.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        boto(jButton3.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        boto(jButton4.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        boto(jButton5.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        boto(jButton6.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        boto(jButton7.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        boto(jButton8.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        boto(jButton9.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void enrereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrereActionPerformed
        // TODO add your handling code here:
        if (!apretat) {
            Object[] options = {"Guardar","Sortir sense guardar", "Cancela"};
            JFrame frame = new JFrame("");

            int n = JOptionPane.showOptionDialog(frame,"Vols guardar la partida?", "Guardar partida",1, JOptionPane.INFORMATION_MESSAGE, null,options,options[0]);

            if (n == 0) { //Guardar
                boolean bool = false;
                while (!bool) {

                    //QUE LI PREGUNTI EL NOM EL NOM
                    String nomP = JOptionPane.showInputDialog(frame, "Escriu el nom de la partida", "Nom Partida", JOptionPane.INFORMATION_MESSAGE);

                    int g = guardarPartida(us,nomP);

                    if (g == 0) {
                        bool = true;
                        Menu obj = new Menu(us);
                        obj.setVisible(true);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(frame,"Aquest nom de partida ja existeix, posa'n un altre", "Alerta!", WARNING_MESSAGE);
                    }
                }
            } else if (n == 1) { //Sortir sense guardar
                Menu obj = new Menu(us);
                obj.setVisible(true);
                dispose();
            } 
        } else {
            Menu obj = new Menu(us);
            obj.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_enrereActionPerformed

    private void enrereKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enrereKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_enrereKeyPressed

    private void c52MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c52MouseClicked
        tf = null;
        if (!es_written(5,2)){
            tf = c52;
            i = 37;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c52MouseClicked

    private void c00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c00MouseClicked
        tf = null;
        if (!es_written(0,0)){
            tf = c00;
            i = 0;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c00MouseClicked

    private void c01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c01MouseClicked
        tf = null;
        if (!es_written(0,1)){
            tf = c01;
            i = 1;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c01MouseClicked

    private void c02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c02MouseClicked
        tf = null;
        if (!es_written(0,2)){
            tf = c02;
            i = 2;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c02MouseClicked

    private void c03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c03MouseClicked
        tf = null;
        if (!es_written(0,3)){
            tf = c03;
            i = 03;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c03MouseClicked

    private void c04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c04MouseClicked
        tf = null;
        if (!es_written(0,4)){
            tf = c04;
            i = 4;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c04MouseClicked

    private void c60MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c60MouseClicked
        tf = null;
        if (!es_written(6,0)){
            tf = c60;
            i = 42;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c60MouseClicked

    private void c10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c10MouseClicked
        tf = null;
        if (!es_written(1,0)){
            tf = c10;
            i = 7;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c10MouseClicked

    private void c20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c20MouseClicked
        tf = null;
        if (!es_written(2,0)){
            tf = c20;
            i = 14;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c20MouseClicked

    private void c30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c30MouseClicked
        tf = null;
        if (!es_written(3,0)){
            tf = c30;
            i = 21;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c30MouseClicked

    private void c40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c40MouseClicked
        tf = null;
        if (!es_written(4,0)){
            tf = c40;
            i = 28;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c40MouseClicked

    private void c50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c50MouseClicked
        tf = null;
        if (!es_written(5,0)){
            tf = c50;
            i = 35;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c50MouseClicked

    private void c51MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c51MouseClicked
        tf = null;
        if (!es_written(5,1)){
            tf = c51;
            i = 36;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c51MouseClicked

    private void c41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c41MouseClicked
        tf = null;
        if (!es_written(4,1)){
            tf = c41;
            i = 29;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c41MouseClicked

    private void c31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c31MouseClicked
        tf = null;
        if (!es_written(3,1)){
            tf = c31;
            i = 22;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c31MouseClicked

    private void c21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c21MouseClicked
        tf = null;
        if (!es_written(2,1)){
            tf = c21;
            i = 15;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c21MouseClicked

    private void c11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c11MouseClicked
        tf = null;
        if (!es_written(1,1)){
            tf = c11;
            i = 8;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c11MouseClicked

    private void c12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c12MouseClicked
        tf = null;
        if (!es_written(1,2)){
            tf = c12;
            i = 9;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c12MouseClicked

    private void c13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c13MouseClicked
        tf = null;
        if (!es_written(1,3)){
            tf = c13;
            i = 10;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c13MouseClicked

    private void c14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c14MouseClicked
        tf = null;
        if (!es_written(1,4)){
            tf = c14;
            i = 11;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c14MouseClicked

    private void c15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c15MouseClicked
        tf = null;
        if (!es_written(1,5)){
            tf = c15;
            i = 12;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c15MouseClicked

    private void c25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c25MouseClicked
        tf = null;
        if (!es_written(2,5)){
            tf = c25;
            i = 19;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c25MouseClicked

    private void c35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c35MouseClicked
        tf = null;
        if (!es_written(3,5)){
            tf = c35;
            i = 26;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c35MouseClicked

    private void c45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c45MouseClicked
        tf = null;
        if (!es_written(4,5)){
            tf = c45;
            i = 33;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c45MouseClicked

    private void c55MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c55MouseClicked
        tf = null;
        if (!es_written(5,5)){
            tf = c55;
            i = 40;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c55MouseClicked

    private void c54MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c54MouseClicked
        tf = null;
        if (!es_written(5,4)){
            tf = c54;
            i = 39;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c54MouseClicked

    private void c44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c44MouseClicked
        tf = null;
        if (!es_written(4,4)){
            tf = c44;
            i = 32;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c44MouseClicked

    private void c34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c34MouseClicked
        tf = null;
        if (!es_written(3,4)){
            tf = c33;
            i = 25;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c34MouseClicked

    private void c24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c24MouseClicked
        tf = null;
        if (!es_written(2,4)){
            tf = c24;
            i = 18;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c24MouseClicked

    private void c23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c23MouseClicked
        tf = null;
        if (!es_written(2,3)){
            tf = c23;
            i = 17;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c23MouseClicked

    private void c22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c22MouseClicked
        tf = null;
        if (!es_written(2,2)){
            tf = c22;
            i = 16;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c22MouseClicked

    private void c33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c33MouseClicked
        tf = null;
        if (!es_written(3,3)){
            tf = c33;
            i = 24;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c33MouseClicked

    private void c32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c32MouseClicked
        tf = null;
        if (!es_written(3,2)){
            tf = c32;
            i = 23;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c32MouseClicked

    private void c42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c42MouseClicked
        tf = null;
        if (!es_written(4,2)){
            tf = c42;
            i = 30;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c42MouseClicked

    private void c43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c43MouseClicked
        tf = null;
        if (!es_written(4,3)){
            tf = c43;
            i = 31;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c43MouseClicked

    private void c53MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c53MouseClicked
        tf = null;
        if (!es_written(5,3)){
            tf = c53;
            i = 38;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c53MouseClicked

    private void c05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c05MouseClicked
        tf = null;
        if (!es_written(0,5)){
            tf = c05;
            i = 5;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c05MouseClicked

    private void c06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c06MouseClicked
        tf = null;
        if (!es_written(0,6)){
            tf = c06;
            i = 6;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c06MouseClicked

    private void c16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c16MouseClicked
        tf = null;
        if (!es_written(1,6)){
            tf = c16;
            i = 13;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c16MouseClicked

    private void c26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c26MouseClicked
        tf = null;
        if (!es_written(2,6)){
            tf = c26;
            i = 20;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c26MouseClicked

    private void c36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c36MouseClicked
        tf = null;
        if (!es_written(3,6)){
            tf = c36;
            i = 27;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c36MouseClicked

    private void c46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c46MouseClicked
        tf = null;
        if (!es_written(4,6)){
            tf = c46;
            i = 34;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c46MouseClicked

    private void c56MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c56MouseClicked
        tf = null;
        if (!es_written(5,6)){
            tf = c56;
            i = 41;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c56MouseClicked

    private void c66MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c66MouseClicked
        tf = null;
        if (!es_written(6,6)){
            tf = c66;
            i = 48;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c66MouseClicked

    private void c65MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c65MouseClicked
        tf = null;
        if (!es_written(5,6)){
            tf = c65;
            i = 47;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c65MouseClicked

    private void c64MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c64MouseClicked
        tf = null;
        if (!es_written(6,4)){
            tf = c64;
            i = 46;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c64MouseClicked

    private void c63MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c63MouseClicked
        tf = null;
        if (!es_written(6,3)){
            tf = c63;
            i = 45;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c63MouseClicked

    private void c62MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c62MouseClicked
        tf = null;
        if (!es_written(6,2)){
            tf = c62;
            i = 44;
        }// TODO add your handling code here:.
    }//GEN-LAST:event_c62MouseClicked

    private void c61MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c61MouseClicked
        tf = null;
        if (!es_written(6,1)){
            tf = c61;
            i = 43;
        }// TODO add your handling code here:
    }//GEN-LAST:event_c61MouseClicked

    private void AutocompletarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AutocompletarMouseClicked
        apretat = true;
        ArrayList<Integer> valors = CarregarSolucioTaulell();
        String afegir;
        for (int i = 0; i < valors.size(); ++i){
            afegir = String.valueOf(valors.get(i));
            txtField[i].setText(afegir);
        }
    }//GEN-LAST:event_AutocompletarMouseClicked

    private void AutocompletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutocompletarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AutocompletarActionPerformed

    private void comprovarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comprovarMouseClicked
        // TODO add your handling code here:
        JFrame frame = new JFrame("");
        if (apretat == true) {
            JOptionPane.showMessageDialog(frame,"Un cop autocompletat, no pots comprovar un Hidato. Ja pots sortir de la partida.", "No et passis de llest",  JOptionPane.ERROR_MESSAGE);
        } else {
            int r;
            r = comprovarHidato(dif);
            if (r >= 1) {
                JOptionPane.showMessageDialog(frame,"Enhorabona. Tens " + r + " punts més!");
                partidaAcabada(r, us);
                Menu obj = new Menu(us);
                obj.setVisible(true);
                dispose();
            }
            else if (r == -1)
                JOptionPane.showMessageDialog(frame,"Hidato mal resolt, torna-ho a intentar", "No ben resolt",  JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_comprovarMouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        boto(jButton12.getText());// TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        boto("Esborrar");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void comprovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprovarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comprovarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jugar7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jugar7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jugar7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jugar7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
      

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jugar7(us, dif).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Autocompletar;
    private javax.swing.JTextField c00;
    private javax.swing.JTextField c01;
    private javax.swing.JTextField c02;
    private javax.swing.JTextField c03;
    private javax.swing.JTextField c04;
    private javax.swing.JTextField c05;
    private javax.swing.JTextField c06;
    private javax.swing.JTextField c10;
    private javax.swing.JTextField c11;
    private javax.swing.JTextField c12;
    private javax.swing.JTextField c13;
    private javax.swing.JTextField c14;
    private javax.swing.JTextField c15;
    private javax.swing.JTextField c16;
    private javax.swing.JTextField c20;
    private javax.swing.JTextField c21;
    private javax.swing.JTextField c22;
    private javax.swing.JTextField c23;
    private javax.swing.JTextField c24;
    private javax.swing.JTextField c25;
    private javax.swing.JTextField c26;
    private javax.swing.JTextField c30;
    private javax.swing.JTextField c31;
    private javax.swing.JTextField c32;
    private javax.swing.JTextField c33;
    private javax.swing.JTextField c34;
    private javax.swing.JTextField c35;
    private javax.swing.JTextField c36;
    private javax.swing.JTextField c40;
    private javax.swing.JTextField c41;
    private javax.swing.JTextField c42;
    private javax.swing.JTextField c43;
    private javax.swing.JTextField c44;
    private javax.swing.JTextField c45;
    private javax.swing.JTextField c46;
    private javax.swing.JTextField c50;
    private javax.swing.JTextField c51;
    private javax.swing.JTextField c52;
    private javax.swing.JTextField c53;
    private javax.swing.JTextField c54;
    private javax.swing.JTextField c55;
    private javax.swing.JTextField c56;
    private javax.swing.JTextField c60;
    private javax.swing.JTextField c61;
    private javax.swing.JTextField c62;
    private javax.swing.JTextField c63;
    private javax.swing.JTextField c64;
    private javax.swing.JTextField c65;
    private javax.swing.JTextField c66;
    private javax.swing.JButton comprovar;
    private javax.swing.JButton enrere;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel numeros;
    private javax.swing.JTextArea titol;
    // End of variables declaration//GEN-END:variables
    private String Caselles[] = {"c00","c01","c02","c03","c04","c05","c06","c10","c11","c12","c13","c14","c15","c16","c20","c21","c22","c23","c24","c25","c26","c30","c31","c32","c33","c34","c35","c36","c40","c41","c42","c43","c44","c45","c46","c50","c51","c52","c53","c54","c55","c56","c60","c61","c62","c63","c64","c65","c66"};
    private javax.swing.JTextField txtField[] = new javax.swing.JTextField[49];
    javax.swing.JTextField tf = new javax.swing.JTextField();
    private boolean apretat,afegirmarca;
    private int val,f,c,i;
}
