/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interficie.jugar;

import static drivers.Controlador.CarregarSolucioTaulell;
import static drivers.Controlador.DefineixCasella;
import static drivers.Controlador.carregarTaulellTemporal;
import static drivers.Controlador.començarJoc;
import static drivers.Controlador.comprovarHidato;
import static drivers.Controlador.es_ultim;
import static drivers.Controlador.es_written;
import static drivers.Controlador.getCasella;
import static drivers.Controlador.guardarPartida;
import static drivers.Controlador.partidaAcabada;
import static drivers.Controlador.switchAnnotationCasella;
import interficie.Menu;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import static javax.swing.JOptionPane.WARNING_MESSAGE;

/**
 *
 * @author jordi.guiu.pujols
 */
public class Jugar6 extends javax.swing.JFrame {
    public static String us;
    public static int dif;
    public static int size = 6;

    /**
     * Creates new form Identificacio
     */
    public Jugar6(String usuari, int dificultat) {
        initComponents();
        setSize(1000,600);
        setLocationRelativeTo(null);
        setResizable(false);
        us = usuari;
        dif = dificultat;
        initialitzararraytextfield();
        myinitComponents();
    }
    
    void initialitzararraytextfield(){
        txtField[0] = c00;
        txtField[1] = c01;
        txtField[2] = c02;
        txtField[3] = c03;
        txtField[4] = c04;
        txtField[5] = c05;
        txtField[6] = c10;
        txtField[7] = c11;
        txtField[8] = c12;
        txtField[9] = c13;
        txtField[10] = c14;
        txtField[11] = c15;
        txtField[12] = c20;
        txtField[13] = c21;
        txtField[14] = c22;
        txtField[15] = c23;
        txtField[16] = c24;
        txtField[17] = c25;
        txtField[18] = c30;
        txtField[19] = c31;
        txtField[20] = c32;
        txtField[21] = c33;
        txtField[22] = c34;
        txtField[23] = c35;
        txtField[24] = c40;
        txtField[25] = c41;
        txtField[26] = c42;
        txtField[27] = c43;
        txtField[28] = c44;
        txtField[29] = c45;
        txtField[30] = c50;
        txtField[31] = c51;
        txtField[32] = c52;
        txtField[33] = c53;
        txtField[34] = c54;
        txtField[35] = c55;
    }
    
    private void myinitComponents() {
        apretat = false;
        ArrayList<Integer> valors = carregarTaulellTemporal();
        començarJoc(dif);
        int ultima = es_ultim();
        String lastnum = Integer.toString(ultima);
        Color color = Color.cyan;
        for (int i = 0; i < valors.size(); ++i){
            tf = txtField[i];
             if (valors.get(i) != 0){
                tf.setText(Integer.toString(valors.get(i)));
                if ("1".equals(tf.getText())) tf.setBackground(color);            
                else if (tf.getText().equals(lastnum)) tf.setBackground(color);
                else if ("-1".equals(tf.getText())){
                    tf.setBackground(Color.black);
                    tf.setText("X");
                }
            }
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numeros = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        enrere = new javax.swing.JButton();
        c52 = new javax.swing.JTextField();
        c00 = new javax.swing.JTextField();
        c01 = new javax.swing.JTextField();
        c02 = new javax.swing.JTextField();
        c03 = new javax.swing.JTextField();
        c04 = new javax.swing.JTextField();
        c05 = new javax.swing.JTextField();
        c10 = new javax.swing.JTextField();
        c20 = new javax.swing.JTextField();
        c30 = new javax.swing.JTextField();
        c40 = new javax.swing.JTextField();
        c50 = new javax.swing.JTextField();
        c51 = new javax.swing.JTextField();
        c41 = new javax.swing.JTextField();
        c31 = new javax.swing.JTextField();
        c21 = new javax.swing.JTextField();
        c11 = new javax.swing.JTextField();
        c12 = new javax.swing.JTextField();
        c13 = new javax.swing.JTextField();
        c14 = new javax.swing.JTextField();
        c15 = new javax.swing.JTextField();
        c25 = new javax.swing.JTextField();
        c35 = new javax.swing.JTextField();
        c45 = new javax.swing.JTextField();
        c55 = new javax.swing.JTextField();
        c54 = new javax.swing.JTextField();
        c44 = new javax.swing.JTextField();
        c34 = new javax.swing.JTextField();
        c24 = new javax.swing.JTextField();
        c23 = new javax.swing.JTextField();
        c22 = new javax.swing.JTextField();
        c33 = new javax.swing.JTextField();
        c32 = new javax.swing.JTextField();
        c42 = new javax.swing.JTextField();
        c43 = new javax.swing.JTextField();
        c53 = new javax.swing.JTextField();
        comprovar = new javax.swing.JButton();
        esborrar = new javax.swing.JButton();
        Autocompletar = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        titols = new javax.swing.JLabel();
        fons = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(688, 488));
        getContentPane().setLayout(null);

        numeros.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numeros.setText("Números:");
        getContentPane().add(numeros);
        numeros.setBounds(710, 100, 90, 50);

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(650, 160, 60, 60);

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(720, 160, 60, 60);

        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(790, 160, 60, 60);

        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(650, 230, 60, 60);

        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(720, 230, 60, 60);

        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(790, 230, 60, 60);

        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(650, 300, 60, 60);

        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(720, 300, 60, 60);

        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(790, 300, 60, 60);

        enrere.setBackground(new java.awt.Color(0, 0, 0));
        enrere.setForeground(new java.awt.Color(255, 255, 255));
        enrere.setText("Sortir");
        enrere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrereActionPerformed(evt);
            }
        });
        enrere.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enrereKeyPressed(evt);
            }
        });
        getContentPane().add(enrere);
        enrere.setBounds(840, 480, 110, 50);

        c52.setEditable(false);
        c52.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c52MouseClicked(evt);
            }
        });
        getContentPane().add(c52);
        c52.setBounds(380, 370, 40, 40);

        c00.setEditable(false);
        c00.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c00MouseClicked(evt);
            }
        });
        getContentPane().add(c00);
        c00.setBounds(300, 170, 40, 40);

        c01.setEditable(false);
        c01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c01MouseClicked(evt);
            }
        });
        getContentPane().add(c01);
        c01.setBounds(340, 170, 40, 40);

        c02.setEditable(false);
        c02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c02MouseClicked(evt);
            }
        });
        getContentPane().add(c02);
        c02.setBounds(380, 170, 40, 40);

        c03.setEditable(false);
        c03.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c03MouseClicked(evt);
            }
        });
        getContentPane().add(c03);
        c03.setBounds(420, 170, 40, 40);

        c04.setEditable(false);
        c04.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c04MouseClicked(evt);
            }
        });
        getContentPane().add(c04);
        c04.setBounds(460, 170, 40, 40);

        c05.setEditable(false);
        c05.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c05MouseClicked(evt);
            }
        });
        getContentPane().add(c05);
        c05.setBounds(500, 170, 40, 40);

        c10.setEditable(false);
        c10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c10MouseClicked(evt);
            }
        });
        getContentPane().add(c10);
        c10.setBounds(300, 210, 40, 40);

        c20.setEditable(false);
        c20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c20MouseClicked(evt);
            }
        });
        getContentPane().add(c20);
        c20.setBounds(300, 250, 40, 40);

        c30.setEditable(false);
        c30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c30MouseClicked(evt);
            }
        });
        getContentPane().add(c30);
        c30.setBounds(300, 290, 40, 40);

        c40.setEditable(false);
        c40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c40MouseClicked(evt);
            }
        });
        getContentPane().add(c40);
        c40.setBounds(300, 330, 40, 40);

        c50.setEditable(false);
        c50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c50MouseClicked(evt);
            }
        });
        getContentPane().add(c50);
        c50.setBounds(300, 370, 40, 40);

        c51.setEditable(false);
        c51.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c51MouseClicked(evt);
            }
        });
        getContentPane().add(c51);
        c51.setBounds(340, 370, 40, 40);

        c41.setEditable(false);
        c41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c41MouseClicked(evt);
            }
        });
        getContentPane().add(c41);
        c41.setBounds(340, 330, 40, 40);

        c31.setEditable(false);
        c31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c31MouseClicked(evt);
            }
        });
        getContentPane().add(c31);
        c31.setBounds(340, 290, 40, 40);

        c21.setEditable(false);
        c21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c21MouseClicked(evt);
            }
        });
        getContentPane().add(c21);
        c21.setBounds(340, 250, 40, 40);

        c11.setEditable(false);
        c11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c11MouseClicked(evt);
            }
        });
        getContentPane().add(c11);
        c11.setBounds(340, 210, 40, 40);

        c12.setEditable(false);
        c12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c12MouseClicked(evt);
            }
        });
        getContentPane().add(c12);
        c12.setBounds(380, 210, 40, 40);

        c13.setEditable(false);
        c13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c13MouseClicked(evt);
            }
        });
        getContentPane().add(c13);
        c13.setBounds(420, 210, 40, 40);

        c14.setEditable(false);
        c14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c14MouseClicked(evt);
            }
        });
        getContentPane().add(c14);
        c14.setBounds(460, 210, 40, 40);

        c15.setEditable(false);
        c15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c15MouseClicked(evt);
            }
        });
        getContentPane().add(c15);
        c15.setBounds(500, 210, 40, 40);

        c25.setEditable(false);
        c25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c25MouseClicked(evt);
            }
        });
        getContentPane().add(c25);
        c25.setBounds(500, 250, 40, 40);

        c35.setEditable(false);
        c35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c35MouseClicked(evt);
            }
        });
        getContentPane().add(c35);
        c35.setBounds(500, 290, 40, 40);

        c45.setEditable(false);
        c45.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c45MouseClicked(evt);
            }
        });
        getContentPane().add(c45);
        c45.setBounds(500, 330, 40, 40);

        c55.setEditable(false);
        c55.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c55MouseClicked(evt);
            }
        });
        getContentPane().add(c55);
        c55.setBounds(500, 370, 40, 40);

        c54.setEditable(false);
        c54.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c54MouseClicked(evt);
            }
        });
        getContentPane().add(c54);
        c54.setBounds(460, 370, 40, 40);

        c44.setEditable(false);
        c44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c44MouseClicked(evt);
            }
        });
        getContentPane().add(c44);
        c44.setBounds(460, 330, 40, 40);

        c34.setEditable(false);
        c34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c34MouseClicked(evt);
            }
        });
        getContentPane().add(c34);
        c34.setBounds(460, 290, 40, 40);

        c24.setEditable(false);
        c24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c24MouseClicked(evt);
            }
        });
        getContentPane().add(c24);
        c24.setBounds(460, 250, 40, 40);

        c23.setEditable(false);
        c23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c23MouseClicked(evt);
            }
        });
        getContentPane().add(c23);
        c23.setBounds(420, 250, 40, 40);

        c22.setEditable(false);
        c22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c22MouseClicked(evt);
            }
        });
        getContentPane().add(c22);
        c22.setBounds(380, 250, 40, 40);

        c33.setEditable(false);
        c33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c33MouseClicked(evt);
            }
        });
        getContentPane().add(c33);
        c33.setBounds(420, 290, 40, 40);

        c32.setEditable(false);
        c32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c32MouseClicked(evt);
            }
        });
        getContentPane().add(c32);
        c32.setBounds(380, 290, 40, 40);

        c42.setEditable(false);
        c42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c42MouseClicked(evt);
            }
        });
        getContentPane().add(c42);
        c42.setBounds(380, 330, 40, 40);

        c43.setEditable(false);
        c43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c43MouseClicked(evt);
            }
        });
        getContentPane().add(c43);
        c43.setBounds(420, 330, 40, 40);

        c53.setEditable(false);
        c53.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c53MouseClicked(evt);
            }
        });
        getContentPane().add(c53);
        c53.setBounds(420, 370, 40, 40);

        comprovar.setText("Comprovar");
        comprovar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comprovarMouseClicked(evt);
            }
        });
        getContentPane().add(comprovar);
        comprovar.setBounds(300, 450, 240, 50);

        esborrar.setText("Esborrar");
        esborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esborrarActionPerformed(evt);
            }
        });
        getContentPane().add(esborrar);
        esborrar.setBounds(730, 370, 120, 60);

        Autocompletar.setText("Autocompletar");
        Autocompletar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AutocompletarMouseClicked(evt);
            }
        });
        Autocompletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutocompletarActionPerformed(evt);
            }
        });
        getContentPane().add(Autocompletar);
        Autocompletar.setBounds(50, 430, 130, 70);

        jButton12.setText("0");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(650, 370, 60, 60);

        titols.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 70)); // NOI18N
        titols.setForeground(new java.awt.Color(255, 255, 255));
        titols.setText("HIDATO");
        getContentPane().add(titols);
        titols.setBounds(270, 40, 330, 80);

        fons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/images/fonspng.png"))); // NOI18N
        getContentPane().add(fons);
        fons.setBounds(0, 0, 1000, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void boto(String textboto){
        //array dstrings com tantes posicions como caselles. 
        //a cada casella li passem a boto la seva posicio dins larray
        String S = Caselles[i];
        f = Character.getNumericValue(S.charAt(1));
        c =  Character.getNumericValue(S.charAt(2));
        if (textboto == "Esborrar") val = 0;
        else val = Integer.parseInt(tf.getText() + textboto);
        System.out.println(val);
        System.out.println(f);
        System.out.println(c);
        if (afegirmarca){ 
            val = Integer.parseInt(textboto);
            switchAnnotationCasella(val, f, c);
            afegirmarca = false;
        }
        else{
            DefineixCasella(val, f, c,size);
            String afegirstr;
            int afegirint = getCasella(f,c);   
            if (afegirint == 0) afegirstr = null;
            else if (afegirint == -1) afegirstr = "X";
            else afegirstr = String.valueOf(afegirint);
            tf.setText(afegirstr);
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boto(jButton1.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        boto(jButton2.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        boto(jButton3.getText());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        boto(jButton4.getText());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        boto(jButton5.getText());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        boto(jButton6.getText());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        boto(jButton7.getText());
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        boto(jButton8.getText());
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        boto(jButton9.getText());
    }//GEN-LAST:event_jButton9ActionPerformed

    private void enrereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrereActionPerformed
        // TODO add your handling code here:
        if (!apretat) {
            Object[] options = {"Guardar","Sortir sense guardar", "Cancela"};
            JFrame frame = new JFrame("");

            int n = JOptionPane.showOptionDialog(frame,"Vols guardar la partida?", "Guardar partida",1, JOptionPane.INFORMATION_MESSAGE, null,options,options[0]);

            if (n == 0) { //Guardar
                boolean bool = false;
                while (!bool) {

                    //QUE LI PREGUNTI EL NOM EL NOM
                    String nomP = JOptionPane.showInputDialog(frame, "Escriu el nom de la partida", "Nom Partida", JOptionPane.INFORMATION_MESSAGE);

                    int g = guardarPartida(us,nomP);

                    if (g == 0) {
                        bool = true;
                        Menu obj = new Menu(us);
                        obj.setVisible(true);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(frame,"Aquest nom de partida ja existeix, posa'n un altre", "Alerta!", WARNING_MESSAGE);
                    }
                }
            } else if (n == 1) { //Sortir sense guardar
                Menu obj = new Menu(us);
                obj.setVisible(true);
                dispose();
            } 
        } else {
            Menu obj = new Menu(us);
            obj.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_enrereActionPerformed

    private void enrereKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enrereKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_enrereKeyPressed

    private void c52MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c52MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(5,2)){
            tf = c52;
            i = 32;
        }
    }//GEN-LAST:event_c52MouseClicked

    private void c00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c00MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(0,0)){
            tf = c00;
            i = 0;
        }
    }//GEN-LAST:event_c00MouseClicked

    private void c01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c01MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(0,1)){
            tf = c01;
            i = 1;
        }
    }//GEN-LAST:event_c01MouseClicked

    private void c02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c02MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(0,2)){
            tf = c02;
            i = 2;
        }
    }//GEN-LAST:event_c02MouseClicked

    private void c03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c03MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(0,3)){
            tf = c03;
            i = 3;
        }
    }//GEN-LAST:event_c03MouseClicked

    private void c04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c04MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(0,4)){
            tf = c04;
            i = 4;
        }
    }//GEN-LAST:event_c04MouseClicked

    private void c05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c05MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(0,5)){
            tf = c05;
            i = 5;
        }
    }//GEN-LAST:event_c05MouseClicked

    private void c10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c10MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(1,0)){
            tf = c10;
            i = 6;
        }
    }//GEN-LAST:event_c10MouseClicked

    private void c20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c20MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(2,0)){
            tf = c20;
            i = 12;
        }
    }//GEN-LAST:event_c20MouseClicked

    private void c30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c30MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(3,0)){
            tf = c30;
            i = 18;
        }
    }//GEN-LAST:event_c30MouseClicked

    private void c40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c40MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(4,0)){
            tf = c40;
            i = 24;
        }
    }//GEN-LAST:event_c40MouseClicked

    private void c50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c50MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(5,0)){
            tf = c50;
            i = 30;
        }
    }//GEN-LAST:event_c50MouseClicked

    private void c51MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c51MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(5,1)){
            tf = c51;
            i = 31;
        }
    }//GEN-LAST:event_c51MouseClicked

    private void c41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c41MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(4,1)){
            tf = c41;
            i = 25;
        }
    }//GEN-LAST:event_c41MouseClicked

    private void c31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c31MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(3,1)){
            tf = c31;
            i = 19;
        }
    }//GEN-LAST:event_c31MouseClicked

    private void c21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c21MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(2,1)){
            tf = c21;
            i = 13;
        }
    }//GEN-LAST:event_c21MouseClicked

    private void c11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c11MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(1,1)){
            tf = c11;
            i = 7;
        }
    }//GEN-LAST:event_c11MouseClicked

    private void c12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c12MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(1,2)){
            tf = c12;
            i = 8;
        }
    }//GEN-LAST:event_c12MouseClicked

    private void c13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c13MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(1,3)){
            tf = c13;
            i = 9;
        }
    }//GEN-LAST:event_c13MouseClicked

    private void c14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c14MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(1,4)){
            tf = c14;
            i = 10;
        }
    }//GEN-LAST:event_c14MouseClicked

    private void c15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c15MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(1,5)){
            tf = c15;
            i = 11;
        }
    }//GEN-LAST:event_c15MouseClicked

    private void c25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c25MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(2,5)){
            tf = c25;
            i = 17;
        }
    }//GEN-LAST:event_c25MouseClicked

    private void c35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c35MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(3,5)){
            tf = c35;
            i = 23;
        }
    }//GEN-LAST:event_c35MouseClicked

    private void c45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c45MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(4,5)){
            tf = c45;
            i = 29;
        }
    }//GEN-LAST:event_c45MouseClicked

    private void c55MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c55MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(5,5)){
            tf = c55;
            i = 35;
        }
    }//GEN-LAST:event_c55MouseClicked

    private void c54MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c54MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(5,4)){
            tf = c54;
            i = 34;
        }
    }//GEN-LAST:event_c54MouseClicked

    private void c44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c44MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(4,4)){
            tf = c44;
            i = 28;
        }
    }//GEN-LAST:event_c44MouseClicked

    private void c34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c34MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(3,4)){
            tf = c34;
            i = 22;
        }
    }//GEN-LAST:event_c34MouseClicked

    private void c24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c24MouseClicked
        // TODO add your handling code here:.
        tf = null;
        if (!es_written(2,4)){
            tf = c24;
            i = 16;
        }
    }//GEN-LAST:event_c24MouseClicked

    private void c23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c23MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(2,3)){
            tf = c23;
            i = 15;
        }
    }//GEN-LAST:event_c23MouseClicked

    private void c22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c22MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(2,2)){
            tf = c22;
            i = 14;
        }
    }//GEN-LAST:event_c22MouseClicked

    private void c33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c33MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(3,3)){
            tf = c33;
            i = 21;
        }
    }//GEN-LAST:event_c33MouseClicked

    private void c32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c32MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(3,2)){
            tf = c32;
            i = 20;
        }
    }//GEN-LAST:event_c32MouseClicked

    private void c42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c42MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(4,2)){
            tf = c42;
            i = 26;
        }
    }//GEN-LAST:event_c42MouseClicked

    private void c43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c43MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(4,3)){
            tf = c43;
            i = 27;
        }
    }//GEN-LAST:event_c43MouseClicked

    private void c53MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c53MouseClicked
        // TODO add your handling code here:
        tf = null;
        if (!es_written(5,3)){
            tf = c53;
            i = 33;
        }
    }//GEN-LAST:event_c53MouseClicked

    private void AutocompletarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AutocompletarMouseClicked
        apretat = true;
        ArrayList<Integer> valors = CarregarSolucioTaulell();
        String afegir;
        for (int i = 0; i < valors.size(); ++i){
            afegir = String.valueOf(valors.get(i));
            txtField[i].setText(afegir);
        }
    }//GEN-LAST:event_AutocompletarMouseClicked

    private void AutocompletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutocompletarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AutocompletarActionPerformed

    private void comprovarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comprovarMouseClicked
        // TODO add your handling code here:
        JFrame frame = new JFrame("");
        if (apretat == true) {
            JOptionPane.showMessageDialog(frame,"Un cop autocompletat, no pots comprovar un Hidato. Ja pots sortir de la partida.", "No et passis de llest",  JOptionPane.ERROR_MESSAGE);
        } else {
            int r;
            r = comprovarHidato(dif);
            if (r >= 1) {
                JOptionPane.showMessageDialog(frame,"Enhorabona. Tens " + r + " punts més!");
                partidaAcabada(r, us);
                Menu obj = new Menu(us);
                obj.setVisible(true);
                dispose();
            }
            else if (r == -1)
                JOptionPane.showMessageDialog(frame,"Hidato mal resolt, torna-ho a intentar", "No ben resolt",  JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_comprovarMouseClicked

    private void esborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esborrarActionPerformed
        // TODO add your handling code here:
        boto("Esborrar"); 
    }//GEN-LAST:event_esborrarActionPerformed

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        boto(jButton12.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jugar6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jugar6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jugar6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jugar6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jugar6(us, dif).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Autocompletar;
    private javax.swing.JTextField c00;
    private javax.swing.JTextField c01;
    private javax.swing.JTextField c02;
    private javax.swing.JTextField c03;
    private javax.swing.JTextField c04;
    private javax.swing.JTextField c05;
    private javax.swing.JTextField c10;
    private javax.swing.JTextField c11;
    private javax.swing.JTextField c12;
    private javax.swing.JTextField c13;
    private javax.swing.JTextField c14;
    private javax.swing.JTextField c15;
    private javax.swing.JTextField c20;
    private javax.swing.JTextField c21;
    private javax.swing.JTextField c22;
    private javax.swing.JTextField c23;
    private javax.swing.JTextField c24;
    private javax.swing.JTextField c25;
    private javax.swing.JTextField c30;
    private javax.swing.JTextField c31;
    private javax.swing.JTextField c32;
    private javax.swing.JTextField c33;
    private javax.swing.JTextField c34;
    private javax.swing.JTextField c35;
    private javax.swing.JTextField c40;
    private javax.swing.JTextField c41;
    private javax.swing.JTextField c42;
    private javax.swing.JTextField c43;
    private javax.swing.JTextField c44;
    private javax.swing.JTextField c45;
    private javax.swing.JTextField c50;
    private javax.swing.JTextField c51;
    private javax.swing.JTextField c52;
    private javax.swing.JTextField c53;
    private javax.swing.JTextField c54;
    private javax.swing.JTextField c55;
    private javax.swing.JButton comprovar;
    private javax.swing.JButton enrere;
    private javax.swing.JButton esborrar;
    private javax.swing.JLabel fons;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel numeros;
    private javax.swing.JLabel titols;
    // End of variables declaration//GEN-END:variables
    private String Caselles[] = {"c00","c01","c02","c03","c04","c05","c10","c11","c12","c13","c14","c15","c20","c21","c22","c23","c24","c25","c30","c31","c32","c33","c34","c35","c40","c41","c42","c43","c44","c45","c50","c51","c52","c53","c54","c55"};
    private javax.swing.JTextField txtField[] = new javax.swing.JTextField[36];
    javax.swing.JTextField tf = new javax.swing.JTextField();
    private boolean apretat,afegirmarca;
    private int val,f,c,i;

}
